version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - terakoya76

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - terakoya76
