name: automerge_system_patch

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        # filter w/ PAT username
        if: github.actor == 'system-user'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_DELETE_BRANCH: true

