name: automerge system

on:
  pull_request:
  # pull_request_target

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'system-user'
        with:
          # approver PAT
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_DELETE_BRANCH: true
