name: release
on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Bump version on merging Pull Requests with specific labels. (bump:major,bump:minor,bump:patch)
      - uses: haya14busa/action-bumpr@v1
        id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"

      # Get tag name.
      - uses: haya14busa/action-cond@v1
        id: tag
        with:
          cond: "${{ startsWith(github.ref, 'refs/tags/') }}"
          if_true: ${{ github.ref }}
          if_false: ${{ steps.bumpr.outputs.next_version }}

      # Doing CHANGELOG things
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: download git-chglog
        run: go get -u github.com/git-chglog/git-chglog/cmd/git-chglog

      - name: set changelog output
        id: changelog
        if: "steps.tag.outputs.value != ''"
        run: |
          # https://github.community/t/set-output-truncates-multiline-strings/16852/3
          changelog=$(git-chglog ${{ steps.tag.outputs.value }})
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"

      # Create release.
      - uses: actions/create-release@v1
        if: "steps.tag.outputs.value != ''"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.value }}
          release_name: Release ${{ steps.tag.outputs.value }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
