# https://docs.github.com/ja/github/administering-a-repository/configuration-options-for-dependency-updates#
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # reviewers:
  #   - "hoge"
  labels:
    - "automerge"

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # reviewers:
  #   - "hoge"
  labels:
    - "automerge"

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # reviewers:
  #   - "hoge"
  labels:
    - "automerge"

- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # reviewers:
  #   - "hoge"
  labels:
    - "automerge"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # reviewers:
  #   - "hoge"
  labels:
    - "automerge"

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # reviewers:
  #   - "hoge"
  labels:
    - "automerge"

- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # reviewers:
  #   - "hoge"
  labels:
    - "automerge"
